### ISSUE TITLE
flutter_launcher_icons add mobile icons

### ISSUE THREAD

**Issue by easeccy** [acikkaynak/afet-destek-org#124]

**Comment by adnanjpg** [comment]
üzerinde çalışılıyor https://github.com/acikkaynak/yardim-agi-flutter/pull/120

**Comment by adnanjpg** [comment]
@impinar bunu merge ettik, kapatır mısın

**Comment by impinar** [comment]
test todo ya çekiyorum, eline sağlık @adnanjpg
